#
FROM ubuntu:18.04

# See http://bugs.python.org/issue19846
ENV LANG C.UTF-8

ARG DEBIAN_FRONTEND=noninteractive
ARG DEBCONF_NONINTERACTIVE_SEEN=true

RUN ln -fs /usr/share/zoneinfo/Europe/London /etc/localtime

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
	python3-tk \
	python3-dev \
    wget \
    pkg-config \
    zip 

#cuda install
RUN apt-get update && apt-get install -y --no-install-recommends \
gnupg2 curl ca-certificates && \
    curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub | apt-key add - && \
    echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/cuda.list && \
    echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list && \
    apt-get purge --autoremove -y curl && \
rm -rf /var/lib/apt/lists/*

ENV CUDA_VERSION 10.1.105

ENV CUDA_PKG_VERSION 10-1=$CUDA_VERSION-1

# For libraries in the cuda-compat-* package: https://docs.nvidia.com/cuda/eula/index.html#attachment-a
RUN apt-get update && apt-get install -y --no-install-recommends \
        cuda-cudart-$CUDA_PKG_VERSION \
cuda-compat-10-1 && \
ln -s cuda-10.1 /usr/local/cuda && \
    rm -rf /var/lib/apt/lists/*

# Required for nvidia-docker v1
RUN echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf && \
    echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf

ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64

# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV NVIDIA_REQUIRE_CUDA "cuda>=10.1 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 brand=tesla,driver>=418,driver<419"
   
RUN pip3 --no-cache-dir install --upgrade \
    pip \
    setuptools

# Some TF tools expect a "python" binary
RUN ln -s $(which python3) /usr/local/bin/python 

# Install other useful Python packages using pip
RUN pip3 --no-cache-dir install \
	torch==1.4.0 \
    torchvision==0.4.0  \
    transformers==2.4.1 \
	Pillow==6.1.0 \
	argparse==1.2.1 \
	backports.ssl-match-hostname==3.5.0.1 \
	certifi==2019.9.11 \
	gast==0.2.2 \
	matplotlib==3.1.1 \
	numpy==1.16.5 \ 
	pytz==2015.7 \
	pyzmq==18.1.0 \
	scipy==1.3.1 \
    nltk==3.4.5 \
    flashtext==2.7 \
    inflect \
    word2number \
    tensorboard==2.1.0

CMD sleep infinity
